### p277异常

产生异常即创建一个异常对象并抛出一个异常对象

***

Throwable  最顶层父类

![image-20191105160530848](C:\Users\Administrator\AppData\Roaming\Typora\typora-user-images\image-20191105160530848.png)

1. Exception ：编译期异常，进行编译java出现的问题

* try catch   或者上面 方法前throw exception

​	2.RuntimeException:运行期异常，java运行过程中出现的问题，将异常处理掉，程序可以继续执行  ，比如数组越界

3. Error:错误，就相当于程序得了无法治愈的毛病，必须修改源代码程序才能继续执行

比如，内存溢出错误，必须修改代码

#### 异常产生过程的解析

![image-20191105164817070](C:\Users\Administrator\AppData\Roaming\Typora\typora-user-images\image-20191105164817070.png)

#### 异常的处理

* 抛出异常throw

  **在方法声明时使用**

  在指定的方法中，抛出指定的异常

  throw new xxxException('异常产生的原因')

  1.必须写在方法的内部

  2.后面new的对象必须是Exception或者Exception子类对象

  3.其抛出指定的异常对象，那么我们就必须处理这个异常对象

  ​	a.throw关键字后面创建的是RuntimeException或者是RuntimeException的子类，则我们可以不进行处理，默认交给JVM处理（jvm打印异常并中断程序）

  ​	比如：NullPoinerException   IndexOutofException

  ​	b.如果是编译异常（写代码时报错），就必须处理这个异常，要么throws，要么try..catch

*  捕获异常    可以catch多个

  try {

  ​	可能产生异常的代码

  }catch(定义一个异常的变量，用来接收try中抛出的异常对象){

  ​	异常的处理逻辑，一般会记录到日志中

  }

  .....

  catch(异常类名  变量名){

  }

  **将异常捕获到catch中，后面又代码将会继续执行**

  处理异常的方法：throwable

  ​	e. getMessage();返回此throwable简短描述

  ​	e. toString();详细信息字符串

  ​	 e.printStackTrace(); JVM打印异常对象，默认此方法，信息最全面

* finally 

  try{}catch(){

  }finally{    

  }

  一般用于资源释放（资源回收），无论程序是否出现异常，最后都要资源是发那个

* 子父类异常

  子类重写父类方法时，抛出的异常必须比父类范围小

  父类方法没有抛出异常，子类重写父类方法时也不能抛出异常

  如果重写的子类内部有异常，则只能try  catch

* 自定义异常

  1.一般都以Exception结尾，说明时一个异常类

  2.继承Exception即为编译期异常，RuntimeException即为运行时异常

  [实例](E:\YangChengCan\Learning\Java学习\代码\base-code\day04-code\src\com\yangcc\Exception)

* 

